PEERJS_KEY='QMLEtmK'; // openssl rand -base64 18      
PEERJS_HOST='genesis.akikieng.com';
PEERJS_PORT=9000;
PEERJS_PATH='/yolo-bear';  
PEERJS_DEBUG=false;
PEERJS_MAX_RECONN_ATTEMPT=0;//3;
PEERJS_TIMEOUT=30000;
YOLOBEAR_SERVER_URL='http://genesis.akikieng.com/yolo-bear-server/api';
USE_AWS_LAMBDA=true;
